### ISSUE TITLE
모든 사람이 물건을 사기만 했던 나라는?

### ISSUE THREAD

**Issue by pmh-only** [Team-WAVE-x/Stop-uncle#2]
![image](https://user-images.githubusercontent.com/39158228/94262426-6db0a500-ff6e-11ea-8c86-5a005084dd6f.png)
출처: 내머리

**Comment by sihyeokpark** [comment]
이해가 안되요

**Comment by sihyeokpark** [comment]
"소비" 는 이해 되는데 "에트" 는 뭐징

**Comment by pmh-only** [comment]
Soviet

**Comment by sihyeokpark** [comment]
아
